#!/usr/bin/env python3
"""
art/immeub/db/mdb/__init__.py
  Contains MongoDB config attributes
"""
import art.immeub.db.mongo.local_settings as ls
LOCAL_MONGODB_URI_STR = ls.MONGODB_CON_STR
DEFAULT_MNG_IMMEUB_DB = ls.DEFAULT_MNG_IMMEUB_DB
DEFAULT_MNG_COBRANCACOLL = ls.DEFAULT_MNG_COBRANCACOLL  # model a "billing card"
DEFAULT_MNG_BILLINGITEMCOLL = ls.DEFAULT_MNG_BILLINGITEMCOLL
DEFAULT_MNG_CONTRACTCOLL = ls.DEFAULT_MNG_CONTRACTCOLL
DEFAULT_MNG_PERSONCOLL = ls.DEFAULT_MNG_PERSONCOLL
DEFAULT_MNG_IMMEUBCOLL = ls.DEFAULT_MNG_IMMEUBCOLL
